name: Run tests on PR creation

on:
  pull_request:
    branches:
      - main  # adjust the branch name as needed
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'  # adjust the Go version as needed

    - name: Run tests
      run: go test ./...
